site_name: OOP Online
site_url: https://regensburger-forscher.de/oop
site_description: Online-Material zum OOP-Kurs
site_author: Alexander Bazo und Florin Schwappach
copyright: MIT
theme: 
  name: yeti
  custom_dir: oop-template
plugins: 
  - git-revision-date
  - search:
      lang: ["de", "en"]
      prebuild_index: true
extra_javascript:
  - scripts/init.js  
#  - scripts/quiz.js
markdown_extensions:
  - footnotes
  - admonition
  - attr_list
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.tilde
nav:
  - Themen: 
    - Einführung: docs/01-Einfuerhung-in-die-Programmierung-und-die-Programmiersprachen/index.md
  - Übungsblätter: 
    - Übersicht: tasks/index.md
    - U01: tasks/U01
    - U02: tasks/U02
    - U03: tasks/U03
    - U04: tasks/U04
    - U05: tasks/U07
    - U06: tasks/U06
    - U07: tasks/U07
    - U08: tasks/U08
    - U09: tasks/U09
    - U10: tasks/U10
    - U11: tasks/U11
    - U12: tasks/U12
  - Informationen:
    - Team: author.md
    - Lizenz: licence.md
  - Impressum: impress.md